security:
    # Hash des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Providers : lecture des utilisateurs depuis l'entité User
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # colonne utilisée comme identifiant

    # Firewalls : zones sécurisées et méthodes d'authentification
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            # Formulaire de login
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    # Contrôle d'accès (optionnel)
    access_control:
       # - { path: ^/admin, roles: ROLE_ADMIN }
       #  - { path: ^/profile, roles: ROLE_USER }

# Configuration spécifique pour les tests (réduction des coûts de hash)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
