<?php

namespace App\Controller\Admin;

use App\Entity\Variants;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\MoneyField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;

/**
 * CRUD controller for managing product variants in the EasyAdmin backend.
 * Variants can include different sizes, colors, or capacities for a product.
 */
class VariantsCrudController extends AbstractCrudController
{
    /**
     * Returns the fully qualified class name of the entity managed by this CRUD controller.
     */
    public static function getEntityFqcn(): string
    {
        return Variants::class;
    }

    /**
     * Configure the fields to display in the admin interface depending on the page type.
     *
     * @param string $pageName Name of the current page (index, detail, edit, new)
     * @return iterable List of fields to show on the page
     */
    public function configureFields(string $pageName): iterable
    {
        return [
            // ID field, auto-generated by the database, hidden when creating/editing
            IdField::new('id')->hideOnForm(),

            // Contenance (e.g., volume, size in ml), hidden on index to reduce table clutter
            TextField::new('contenance', 'Contenance')->hideOnIndex(),

            // Size (taille), hidden on index
            TextField::new('size', 'Taille')->hideOnIndex(),

            // Color (couleur), hidden on index
            TextField::new('color', 'Couleur')->hideOnIndex(),

            // Price in euros, displayed with 2 decimals
            NumberField::new('price', 'Prix (€)')
                ->setCurrency('EUR')       // currency symbol shown in admin
                ->setStoredAsCents(false)  // store price as float, not cents
                ->setNumDecimals(2),       // always display 2 decimals

            // Boolean field indicating whether this variant is the default for its product
            BooleanField::new('isDefault', 'Par défaut'),
        ];
    }
}
