controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


rgpd_request:
    path: /rgpd/demande
    controller: App\Controller\content\ConfidentialiteController::demande
